---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azure-disk-dynamic
  labels:
    app.kubernetes.io/name: csi-test
spec:
  storageClassName: managed-csi-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: azure-disk-dynamic
  labels:
    app.kubernetes.io/name: csi-test
spec: 
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: busybox
        image: container-registry.ubs.net/busybox:1.30.1
        args: ["/bin/sh", "-ec", "SLEEP_TIMEOUT=3600;while :; do echo sleeping for $SLEEP_TIMEOUT seconds...; sleep $SLEEP_TIMEOUT ; done"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: azure-disk-dynamic
          mountPath: /data
      volumes:
      - name: azure-disk-dynamic
        persistentVolumeClaim:
          claimName: pvc-azure-disk-dynamic